apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: vote-app
    app.kubernetes.io/part-of: examplevotingapp
  name: vote-app
spec:
  selector:
    app.kubernetes.io/name: vote-app
    app.kubernetes.io/part-of: examplevotingapp
  ports:
  - port: 5000
    targetPort: 80
  # Ingress使える場合
  # type: ClusterIP
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: vote-app
    app.kubernetes.io/part-of: examplevotingapp
  name: vote-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: vote-app
      app.kubernetes.io/part-of: examplevotingapp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vote-app
        app.kubernetes.io/part-of: examplevotingapp
    spec:
      containers:
      - name: vote-app
        image: dockersamples/examplevotingapp_vote
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: vote-app-pdb
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vote-app
      app.kubernetes.io/part-of: examplevotingapp
