apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: vote-cache
    app.kubernetes.io/component: cache
    app.kubernetes.io/part-of: examplevotingapp
  name: vote-cache
spec:
  selector:
    app.kubernetes.io/name: vote-cache
    app.kubernetes.io/component: cache
    app.kubernetes.io/part-of: examplevotingapp
  ports:
  - port: 6379
    targetPort: 6379
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: vote-cache
    app.kubernetes.io/component: cache
    app.kubernetes.io/part-of: examplevotingapp
  name: vote-cache
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vote-cache
      app.kubernetes.io/component: cache
      app.kubernetes.io/part-of: examplevotingapp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vote-cache
        app.kubernetes.io/component: cache
        app.kubernetes.io/part-of: examplevotingapp
    spec:
      containers:
      - name: vote-cache
        image: redis:alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 6379
