apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: vote-worker
    app.kubernetes.io/component: worker
    app.kubernetes.io/part-of: examplevotingapp
  name: vote-worker
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vote-worker
      app.kubernetes.io/component: worker
      app.kubernetes.io/part-of: examplevotingapp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vote-worker
        app.kubernetes.io/component: worker
        app.kubernetes.io/part-of: examplevotingapp
    spec:
      containers:
      - name: vote-worker
        image: dockersamples/examplevotingapp_worker
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: vote-worker-pdb
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vote-worker
      app.kubernetes.io/part-of: examplevotingapp
