apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: vote-db
    app.kubernetes.io/component: db
    app.kubernetes.io/part-of: examplevotingapp
  # NOTE: db以外の値にするとworkerが起動できなくなる
  name: db
spec:
  selector:
    app.kubernetes.io/name: vote-db
    app.kubernetes.io/component: db
    app.kubernetes.io/part-of: examplevotingapp
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: vote-db
    app.kubernetes.io/component: db
    app.kubernetes.io/part-of: examplevotingapp
  name: vote-db
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vote-db
      app.kubernetes.io/component: db
      app.kubernetes.io/part-of: examplevotingapp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vote-db
        app.kubernetes.io/component: db
        app.kubernetes.io/part-of: examplevotingapp
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: vote-db-configmap
        name: vote-db
        image: postgres:9.4
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"
        ports:
        - containerPort: 5432
