apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: vote-result
    app.kubernetes.io/part-of: examplevotingapp
  name: vote-result
spec:
  selector:
    app.kubernetes.io/name: vote-result
    app.kubernetes.io/part-of: examplevotingapp
  ports:
  - port: 5001
    targetPort: 80
  # Ingress使える場合
  # type: ClusterIP
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: vote-result
    app.kubernetes.io/part-of: examplevotingapp
  name: vote-result
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vote-result
      app.kubernetes.io/part-of: examplevotingapp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vote-result
        app.kubernetes.io/part-of: examplevotingapp
    spec:
      containers:
      - name: vote-result
        image: dockersamples/examplevotingapp_vote
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"
        ports:
        - containerPort: 5001
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: vote-result-pdb
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vote-result
      app.kubernetes.io/part-of: examplevotingapp
